import Foundation
import HealthKit

extension HKWorkoutActivityType {
    /// Stable slug for the activity type. HealthKit only exposes a raw `UInt`,
    /// and the raw value is what a workflow should key on — but a name makes
    /// exports readable without a lookup table on the other side.
    ///
    /// Unmapped values fall through to `activity_<raw>` rather than "other", so
    /// a new activity type in a future OS is identifiable rather than lumped in
    /// with genuinely-unknown workouts.
    var name: String {
        switch self {
        case .americanFootball: return "american_football"
        case .archery: return "archery"
        case .australianFootball: return "australian_football"
        case .badminton: return "badminton"
        case .barre: return "barre"
        case .baseball: return "baseball"
        case .basketball: return "basketball"
        case .bowling: return "bowling"
        case .boxing: return "boxing"
        case .cardioDance: return "cardio_dance"
        case .climbing: return "climbing"
        case .cooldown: return "cooldown"
        case .coreTraining: return "core_training"
        case .cricket: return "cricket"
        case .crossCountrySkiing: return "cross_country_skiing"
        case .crossTraining: return "cross_training"
        case .curling: return "curling"
        case .cycling: return "cycling"
        case .discSports: return "disc_sports"
        case .downhillSkiing: return "downhill_skiing"
        case .elliptical: return "elliptical"
        case .equestrianSports: return "equestrian_sports"
        case .fencing: return "fencing"
        case .fishing: return "fishing"
        case .fitnessGaming: return "fitness_gaming"
        case .flexibility: return "flexibility"
        case .functionalStrengthTraining: return "functional_strength_training"
        case .golf: return "golf"
        case .gymnastics: return "gymnastics"
        case .handCycling: return "hand_cycling"
        case .handball: return "handball"
        case .highIntensityIntervalTraining: return "hiit"
        case .hiking: return "hiking"
        case .hockey: return "hockey"
        case .hunting: return "hunting"
        case .jumpRope: return "jump_rope"
        case .kickboxing: return "kickboxing"
        case .lacrosse: return "lacrosse"
        case .martialArts: return "martial_arts"
        case .mindAndBody: return "mind_and_body"
        case .mixedCardio: return "mixed_cardio"
        case .other: return "other"
        case .paddleSports: return "paddle_sports"
        case .pickleball: return "pickleball"
        case .pilates: return "pilates"
        case .play: return "play"
        case .preparationAndRecovery: return "preparation_and_recovery"
        case .racquetball: return "racquetball"
        case .rowing: return "rowing"
        case .rugby: return "rugby"
        case .running: return "running"
        case .sailing: return "sailing"
        case .skatingSports: return "skating_sports"
        case .snowSports: return "snow_sports"
        case .snowboarding: return "snowboarding"
        case .soccer: return "soccer"
        case .socialDance: return "social_dance"
        case .softball: return "softball"
        case .squash: return "squash"
        case .stairClimbing: return "stair_climbing"
        case .stairs: return "stairs"
        case .stepTraining: return "step_training"
        case .surfingSports: return "surfing_sports"
        case .swimBikeRun: return "swim_bike_run"
        case .swimming: return "swimming"
        case .tableTennis: return "table_tennis"
        case .taiChi: return "tai_chi"
        case .tennis: return "tennis"
        case .trackAndField: return "track_and_field"
        case .traditionalStrengthTraining: return "traditional_strength_training"
        case .transition: return "transition"
        case .underwaterDiving: return "underwater_diving"
        case .volleyball: return "volleyball"
        case .walking: return "walking"
        case .waterFitness: return "water_fitness"
        case .waterPolo: return "water_polo"
        case .waterSports: return "water_sports"
        case .wheelchairRunPace: return "wheelchair_run_pace"
        case .wheelchairWalkPace: return "wheelchair_walk_pace"
        case .wrestling: return "wrestling"
        case .yoga: return "yoga"
        default: return "activity_\(rawValue)"
        }
    }
}
