# Generated by Django 5.2.16 on 2026-08-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('last_app_version', models.CharField(blank=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('batch_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('stored', 'Stored'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('declared_record_count', models.IntegerField(default=0)),
                ('stored_record_count', models.IntegerField(default=0)),
                ('deleted_record_count', models.IntegerField(default=0)),
                ('skipped_record_count', models.IntegerField(default=0)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.IntegerField(default=1)),
                ('window_from', models.DateTimeField(blank=True, null=True)),
                ('window_to', models.DateTimeField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingest.device')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('quantity', 'Quantity'), ('category', 'Category'), ('sleep', 'Sleep'), ('workout', 'Workout'), ('correlation', 'Correlation'), ('statistic', 'Statistic'), ('characteristic', 'Characteristic'), ('delete', 'Delete')], max_length=32)),
                ('metric', models.CharField(max_length=128)),
                ('metric_slug', models.CharField(max_length=128)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('value_label', models.CharField(blank=True, max_length=128)),
                ('start', models.DateTimeField(db_index=True, null=True)),
                ('end', models.DateTimeField(null=True)),
                ('tz', models.CharField(blank=True, max_length=64)),
                ('aggregation', models.CharField(blank=True, max_length=16)),
                ('source_name', models.CharField(blank=True, max_length=128)),
                ('source_bundle_id', models.CharField(blank=True, max_length=255)),
                ('source_product_type', models.CharField(blank=True, max_length=64)),
                ('source_os_version', models.CharField(blank=True, max_length=64)),
                ('hardware', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('schema_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingest.batch')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingest.device')),
            ],
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', 'received_at'], name='ingest_batc_status_35e18e_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['metric_slug', 'start'], name='ingest_reco_metric__b214b3_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['device', 'start'], name='ingest_reco_device__7d1e73_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['kind', 'start'], name='ingest_reco_kind_701f11_idx'),
        ),
    ]
