# Generated by Django 5.2.16 on 2026-08-01 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_insightturn_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('detail', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-last_sent_at',),
            },
        ),
    ]
