# Generated by Django 5.2.16 on 2026-08-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_chat_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summarised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary_through_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insightturn',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insightturn',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
