# Generated by Django 5.2.16 on 2026-08-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_conversation_compaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightturn',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insightturn',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insightturn',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Not useful'), (1, 'Useful')], db_index=True, null=True),
        ),
    ]
