# Generated by Django 5.2.16 on 2026-08-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_answer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightturn',
            name='prompt_version',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
